Add Arrowhead wrappers
CTU-IIG/f1tenth-scoreapp pull request #6
Opened 2022-05-12 13:08 UTC by jara001

2022-05-12 18:38 UTC, wentasah requested changes

2022-05-23 06:20 UTC, jara001 commented on README.md
> +3. [backend-arrowhead](./backend-arrowhead/) (Arrowhead Compliant overlay for launching the backend)
Moved to `./arrowhead`. Used `wrapper` in readme even though I still believe that it was properly used. (Not everything is ROS (: ).

2022-05-23 06:22 UTC, jara001 commented on barrier/optic_barrier_sw/CMakeLists.txt
> +        COMMAND git describe --always --tags
It is not copied, some parts are probably inspired somewhere else. During the development I believe that I have used most of them, but not now.

^^ describe, describe=40 is not the same. The goal was to create a unique commit name that fits on the screen. (Also, dirty can be shown using something else, thus it is not used in describe.)

2022-05-23 06:22 UTC, jara001 commented on README.md
> +F1tenth Scoreapp is released under the **GPLv3** license.
I will change it to TODO and open up an issue here.

2022-05-23 06:33 UTC, jara001 commented on barrier/optic_barrier_sw/main.c
> +        system("pkill websocat"); // FIXME: This is currently only way how I can force quit on websocat.
I have moved this to #8 as it requires further attention and as it is not required right now.

2022-05-23 06:33 UTC, merged